apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancellog
  labels:
    app: cancellog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cancellog
  template:
    metadata:
      labels:
        app: cancellog
    spec:
      containers:
        - name: cancellog
          image: "username/cancellog:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
